# only runs tests for now

#include:
#  - template: Security/SAST.gitlab-ci.yml

variables:
  POSTGRES_DB: edea
  POSTGRES_USER: edea
  POSTGRES_PASSWORD: edea
  MEILI_MASTER_KEY: meiliedea

stages: 
  - test

tests:
  services:
    - postgres:14.2-alpine
    - docker.io/getmeili/meilisearch:v0.26.1
  stage: test
  image: golang:1.18-alpine
  script:
    - apk add --no-cache npm make bash yarn ncurses git
    - npm install -D @playwright/test
    - npx playwright install
    - (cd frontend; ./install-dependencies.sh)
    - make build
    - ./edead &
    - sleep 5
    - (cd frontend; npx playwright test)
