# only runs tests for now

#include:
#  - template: Security/SAST.gitlab-ci.yml

stages: 
  - test

services:
  - docker:dind    

tests:
  stage: test
  image: docker:latest
  script:
    - mkdir -p ~/.docker/cli-plugins
    - apk add --no-cache npm curl
    - curl https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
    - chmod +x ~/.docker/cli-plugins/docker-compose
    - docker version
    - docker compose up
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright test
