# only runs tests for now

#include:
#  - template: Security/SAST.gitlab-ci.yml

stages: 
  - test

services:
  - docker:dind    

tests:
  services:
    - docker:dind
  stage: test
  image: docker/compose:latest
  script:
    - apk add --no-cache npm
    - docker compose up
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright test
