# only runs tests for now

include:
  - template: Security/SAST.gitlab-ci.yml

stages: 
  - test

services:
  - docker:dind    

tests:
  stage: test
  image: docker
  script:
    - docker compose up -d
    - apk add --no-cache npm
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright test
