server:
  host: localhost
  port: 3000
dsn: host=127.0.0.1 user=edea password=edea dbname=edea port=5432 sslmode=disable
api:
  githubtoken:
merge_tool: /home/user/git/edea/tool/edea_merge_tool
cache:
  repo:
    base: /home/user/git/edea/backend/tmp/git
  book:
    base: /home/user/git/edea/backend/tmp/doc
  diff:
    schema: ./tmp/sch
    layout: ./tmp/pcb
auth:
  kratos:
  oidc: # rename to oidc for auth0
    use: true
    provider_url:
    client_id:
    client_secret:
    redirect_url:
    session_secret:
    logout_url:
    post_logout_url:
  mock_oidc: # rename to oidc to use mock auth
    provider_url:
    client_id:
    client_secret:
    redirect_url:
    session_secret:
  use_mock: false
search:
  host: http://127.0.0.1:7700
  index: edea
  api_key:
