server:
  host: localhost
  port: 3000
dsn: host=127.0.0.1 user=edea password=edea dbname=edea port=5432 sslmode=disable
cache:
  repo:
    base: /home/user/git/edea/backend/tmp/git
  book:
    base: /home/user/git/edea/backend/tmp/doc
  diff:
    schema: ./tmp/sch
    layout: ./tmp/pcb
auth:
  oidc:
    provider_url: http://your-hostname:3000
    client_id: a-random-id
    client_secret: the-client-secret
    redirect_url: http://your-hostname:3000/callback
    logout_url: http://your-hostname:3000/logout_callback
    post_logout_url: http://your-hostname:3000/
  use_mock: true
search:
  host: http://127.0.0.1:7700
  index: edea
  api_key:
