server:
  host: localhost
  port: 3000
dsn: host=192.168.0.2 user=edea password=edea dbname=edea port=5432 sslmode=disable
api:
  githubtoken: ***REMOVED***
cache:
  repo:
    base: ./tmp/git
  diff:
    schema: ./tmp/sch
    layout: ./tmp/pcb
auth:
  kratos:
  oidc: # rename to oidc for auth0
    use: true
    provider_url: ***REMOVED***
    client_id: ***REMOVED***
    client_secret: ***REMOVED***
    redirect_url: http://localhost:3000/callback
    session_secret: ***REMOVED***
  mock_oidc: # rename to oidc to use mock auth
    provider_url: http://localhost:3000/
    client_id: ***REMOVED***
    client_secret: ***REMOVED***
    redirect_url: http://localhost:3000/callback
    session_secret: ***REMOVED***
  use_mock: false
