version: "3.9"
services:
  edea-server:
    image: edea-server
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    volumes:
      - data:/data
    ports:
      - 3000:3000
    environment:
      - DB_DSN=host=edea-db user=edea password=edea dbname=edea port=5432 sslmode=disable
      - REPO_CACHE_BASE=/data/repo
      - SEARCH_HOST=http://edea-meilisearch:7700
      - SEARCH_INDEX=edea
      - SEARCH_API_KEY=meiliedea
  db:
    image: docker.io/postgres:14.2-alpine
    container_name: edea-db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: edea
      POSTGRES_USER: edea
      POSTGRES_PASSWORD: edea
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - edea-net
  search:
    image: docker.io/getmeili/meilisearch:v0.26.1
    container_name: edea-meilisearch
    volumes:
      - data:/var/lib/meilisearch/data
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: meiliedea
    expose:
      - 7700
    ports:
      - 7700:7700
    networks:
      - edea-net

volumes:
  data:

networks:
  edea-net:
