version: "3.9"
services:
  db:
    image: docker.io/postgres:14.1-alpine
    container_name: edea-postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: edea
      POSTGRES_USER: edea
      POSTGRES_PASSWORD: edea
    expose:
      - 5432
    ports:
      - 5432:5432
  search:
    image: docker.io/getmeili/meilisearch:v0.24.0
    container_name: edea-meilisearch
    volumes:
      - data:/var/lib/meilisearch/data
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_MASTER_KEY: meiliedea
    expose:
      - 7700
    ports:
      - 7700:7700

volumes:
  data:
