name: Docker Image CI

on:
  push:
    branches: [main, ci-shenanigans]
  pull_request:
    branches: [main]

env:
  FF_NETWORK_PER_BUILD: 1
  POSTGRES_DB: edea
  POSTGRES_USER: edea
  POSTGRES_PASSWORD: edea
  MEILI_MASTER_KEY: meiliedea
  SERVER_HOST: 0.0.0.0
  SERVER_PORT: 3000
  DB_DSN: host=postgres user=edea password=edea dbname=edea port=5432 sslmode=disable
  MERGE_TOOL: merge-tool/edea_merge_tool
  PLOTPCB: cmd/plotpcb/plotpcb.py
  REPO_CACHE_BASE: ./tmp/git
  BOOK_CACHE_BASE: ./tmp/doc
  AUTH_PROVIDER_URL: http://localhost:3000
  AUTH_CLIENT_ID: LGqqvVYdSGmv8FZmvHRYq9aYgxyx8ULd
  AUTH_CLIENT_SECRET: SUXHrS77iEyZfNoAeZE5LYb8yRSTGW4LBftNRDG2xFYcnH62qo279bGBzyLW7Qzr
  AUTH_REDIRECT_URL: http://localhost:3000/callback
  AUTH_LOGOUT_URL: http://localhost:3000/logout_callback
  AUTH_POST_LOGOUT_URL: http://localhost:3000/
  USE_AUTH_MOCK: "true"
  SEARCH_HOST: http://search:7700
  SEARCH_INDEX: edea
  SEARCH_API_KEY: meiliedea
  TEST_HOST: http://localhost:3000

jobs:
  build:
    services:
      postgres:
        image: postgres:14.2-alpine
        ports:
          - 5432:5432
      search:
        image: docker.io/getmeili/meilisearch:v0.26.1
        ports:
          - 7700:7700

    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag edea-server:${{ github.ref_name }}
      - name: Run Docker image
        run: docker run -d -p --rm edea-server:${{ github.ref_name }}
      - name: Install dependencies
        run: (cd frontend; npm i -D @playwright/test)
      - name: Install Playwright
        run: (cd frontend; npx playwright install --with-deps)
      - name: Run Playwright tests
        run: (cd frontend; npx playwright test)
